birds/urls.py
# -*- mode: python -*-
from django.contrib.auth.decorators import login_required
from django.urls import path

from birds import api_views, views

app_name = "birds"
urlpatterns = [
    # browser ui
    path("", views.index, name="index"),
    path("animals/", views.animal_list, name="animals"),
    path(
        "animals/new/",
        login_required(views.new_animal_entry),
        name="new_animal",
    ),
    path(
        "animals/<uuid>/",
        views.animal_view,
        name="animal",
    ),
    path(
        "animals/<uuid>/genealogy/",
        views.animal_genealogy,
        name="genealogy",
    ),
    path(
        "animals/<uuid>/kinship/",
        views.animal_kinship,
        name="kinship",
    ),
    path(
        "animals/<uuid:parent>/children/",
        views.animal_list,
        name="animal_kids",
    ),
    path(
        "animals/<uuid>/set-sex/",
        login_required(views.update_sex),
        name="set_sex",
    ),
    path(
        "animals/<uuid:uuid>/tags/",
        login_required(views.update_tags),
        name="update_tags",
    ),
    path(
        "animals/<uuid:uuid>/tags/toggle/<int:tag_id>/",
        login_required(views.toggle_tag),
        name="toggle_tag",
    ),
    path(
        "animals/<uuid:uuid>/tags/new/",
        login_required(views.create_tag),
        name="create_tag",
    ),
    path(
        "animals/<uuid>/new-band/",
        login_required(views.new_band_entry),
        name="new_band",
    ),
    path(
        "animals/<uuid:animal>/events/",
        views.event_list,
        name="events",
    ),
    path(
        "animals/<uuid:animal>/events/new/",
        login_required(views.event_entry),
        name="event_entry",
    ),
    path(
        "events/<int:event>/change/",
        views.event_entry,
        name="event_entry",
    ),
    path(
        "animals/<uuid:animal>/measurements/",
        views.measurement_list,
        name="measurements",
    ),
    path("events/", views.event_list, name="events"),
    path("measurements/", views.measurement_list, name="measurements"),
    path("locations/", views.location_list, name="locations"),
    path("locations/<int:pk>/", views.location_view, name="location"),
    path("locations/<int:location>/events/", views.event_list, name="events"),
    path(
        "animals/<uuid:animal>/samples/",
        views.sample_list,
        name="samples",
    ),
    path(
        "animals/<uuid>/samples/new/",
        login_required(views.new_sample_entry),
        name="new_sample",
    ),
    path("tags/", views.tag_list, name="tags"),
    path("tags/<int:pk>/", views.tag_view, name="tag"),
    path("pairings/", views.pairing_list, name="pairings"),
    path("pairings/active/", views.active_pairing_list, name="pairings_active"),
    path("pairings/<int:pk>/", views.pairing_view, name="pairing"),
    path(
        "pairings/<int:pk>/new/",
        login_required(views.new_pairing_entry),
        name="new_pairing",
    ),
    path(
        "pairings/<int:pk>/new-egg/",
        login_required(views.new_pairing_egg),
        name="new_pairing_egg",
    ),
    path(
        "pairings/<int:pk>/new-event/",
        login_required(views.new_pairing_event),
        name="new_pairing_event",
    ),
    path(
        "pairings/<int:pk>/end/",
        login_required(views.close_pairing),
        name="end_pairing",
    ),
    path("pairings/new/", login_required(views.new_pairing_entry), name="new_pairing"),
    path("sampletypes/", views.sample_type_list, name="sampletypes"),
    path("samples/", views.sample_list, name="samples"),
    path(
        "samples/<uuid>/",
        views.sample_view,
        name="sample",
    ),
    # summary views
    path(
        "summary/locations/",
        views.location_summary,
        name="location-summary",
    ),
    path("summary/breeding/", views.breeding_report, name="breeding-summary"),
    path(
        "summary/events/<int:year>/<int:month>/",
        views.event_summary,
        name="event_summary",
    ),
    # path("summary/breeding-stats/", views.breeding_stats_list, name="breeding-stats"),
    # forms
    path(
        "breeding-check/", login_required(views.breeding_check), name="breeding-check"
    ),
    # api
    path("api/info/", api_views.info, name="api_info"),
    path("api/animals/", api_views.AnimalsList.as_view(), name="animals_api"),
    path(
        "api/animals/<uuid:pk>/",
        api_views.animal_detail,
        name="animal_api",
    ),
    path(
        "api/animals/<uuid:pk>/children/",
        api_views.AnimalChildList.as_view(),
        name="children_api",
    ),
    path(
        "api/animals/<uuid:animal>/events/",
        api_views.EventList.as_view(),
        name="events_api",
    ),
    path("api/events/", api_views.EventList.as_view(), name="events_api"),
    path("api/events/<int:pk>/", api_views.event_detail, name="event_api"),
    path("api/measurements/", api_views.measurement_list, name="measurements_api"),
    path("api/pedigree/", api_views.animal_pedigree, name="pedigree_api"),
]

birds/forms.py
# -*- mode: python -*-
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.template.defaultfilters import pluralize
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from birds import models
from birds.models import (
    Animal,
    Color,
    Event,
    Location,
    Measurement,
    Pairing,
    Plumage,
    Sample,
    Species,
    Status,
    Tag,
)


def get_status_or_error(name: str):
    try:
        return Status.objects.get(name=name)
    except ObjectDoesNotExist as err:
        raise forms.ValidationError(
            _("No %(name)s status type - add one in admin"),
            params={"name": name},
        ) from err


class EventForm(forms.ModelForm):
    date = forms.DateField()
    location = forms.ModelChoiceField(
        queryset=Location.objects.filter(active=True), required=False
    )
    description = forms.CharField(widget=forms.Textarea, required=False)
    entered_by = forms.ModelChoiceField(queryset=User.objects.filter(is_active=True))

    class Meta:
        model = Event
        fields = ["date", "status", "location", "description", "entered_by"]


class MeasurementForm(forms.ModelForm):
    value = forms.FloatField(required=False)

    class Meta:
        model = Measurement
        fields = ["type", "value"]


class SampleForm(forms.ModelForm):
    class Meta:
        model = Sample
        fields = ["type", "source", "location", "comments", "date", "collected_by"]


class NewPairingForm(forms.Form):
    qs = Animal.objects.with_dates().alive()
    sire = forms.ModelChoiceField(
        queryset=qs.filter(sex=Animal.Sex.MALE).order_by("band_color", "band_number")
    )
    dam = forms.ModelChoiceField(
        queryset=qs.filter(sex=Animal.Sex.FEMALE).order_by("band_color", "band_number")
    )
    began_on = forms.DateField()
    purpose = forms.CharField(widget=forms.Textarea, required=False)
    entered_by = forms.ModelChoiceField(queryset=User.objects.filter(is_active=True))
    location = forms.ModelChoiceField(
        queryset=Location.objects.filter(nest=True), required=False
    )

    def clean(self):
        data = super().clean()
        sire = data.get("sire")
        if sire is None:
            raise forms.ValidationError(_("Must provide a sire"))
        if sire.sex != Animal.Sex.MALE:
            raise forms.ValidationError(_("Sire is not male"))
        if sire.history.age_group() != models.ADULT_ANIMAL_NAME:
            raise forms.ValidationError(_("Sire is not an adult"))
        if not sire.history.is_alive():
            raise forms.ValidationError(_("Sire is not alive"))
        if sire.pairings().filter(ended_on__isnull=True).count():
            raise forms.ValidationError(_("Sire is already in an active pairing"))
        sire_overlaps = sire.pairings().filter(
            began_on__lte=data["began_on"], ended_on__gte=data["began_on"]
        )
        if sire_overlaps.count() > 0:
            raise forms.ValidationError(
                _(
                    "Start date %(began_on)s overlaps with an existing pairing for sire: %(prev)s"
                ),
                code="invalid",
                params=data | {"prev": sire_overlaps.first()},
            )
        dam = data.get("dam")
        if dam is None:
            raise forms.ValidationError(_("Must provide a dam"))
        if dam.sex != Animal.Sex.FEMALE:
            raise forms.ValidationError(_("Dam is not female"))
        if dam.history.age_group() != models.ADULT_ANIMAL_NAME:
            raise forms.ValidationError(_("Dam is not an adult"))
        if not dam.history.is_alive():
            raise forms.ValidationError(_("Dam is not alive"))
        if dam.pairings().filter(ended_on__isnull=True).count():
            raise forms.ValidationError(_("Dam is in an active pairing"))
        dam_overlaps = dam.pairings().filter(
            began_on__lte=data["began_on"], ended_on__gte=data["began_on"]
        )
        if dam_overlaps.count() > 0:
            raise forms.ValidationError(
                _(
                    "Start date %(began_on)s overlaps with an existing pairing for dam: %(prev)s"
                ),
                code="invalid",
                params=data | {"prev": dam_overlaps.first()},
            )
        return data


class EndPairingForm(forms.Form):
    ended_on = forms.DateField(required=True)
    location = forms.ModelChoiceField(queryset=Location.objects.all(), required=False)
    entered_by = forms.ModelChoiceField(queryset=User.objects.filter(is_active=True))
    comment = forms.CharField(widget=forms.Textarea, required=False)
    remove_unhatched = forms.BooleanField(required=False)


class BreedingCheckForm(forms.Form):
    # this should be active() only but it may be causing some weird and
    # difficult to replicate form validation errors
    pairing = forms.ModelChoiceField(
        queryset=Pairing.objects.all(), widget=forms.HiddenInput()
    )
    location = forms.ModelChoiceField(
        queryset=Location.objects.all(), widget=forms.HiddenInput()
    )
    eggs = forms.IntegerField(label="eggs", min_value=0)
    chicks = forms.IntegerField(label="chicks", min_value=0)

    def clean(self):
        data = super().clean()
        # there is an infrequent but difficult to reproduce condition where the
        # parent class has an error validating the "pairing" field. It's a logic
        # error so we want to raise an exception in the following line:
        pairing = data["pairing"]
        initial_chicks = pairing.eggs().alive()
        initial_eggs = pairing.eggs().unhatched().existing().order_by("created_at")
        initial_eggs_count = initial_eggs.count()
        delta_chicks = data["chicks"] - initial_chicks.count()
        delta_eggs = data["eggs"] - initial_eggs_count + delta_chicks
        if delta_chicks < 0:
            raise forms.ValidationError(
                _("Lost chicks need to be removed manually by adding an event")
            )
        if delta_chicks > initial_eggs_count:
            raise forms.ValidationError(
                _("Not enough eggs to make %(chicks)d new chick%(plural)s"),
                params={"chicks": delta_chicks, "plural": pluralize(delta_chicks)},
            )
        data["hatch_status"] = get_status_or_error(models.BIRTH_EVENT_NAME)
        data["laid_status"] = get_status_or_error(models.UNBORN_CREATION_EVENT_NAME)
        data["lost_status"] = get_status_or_error(models.BAD_EGG_EVENT_NAME)

        data["hatched_eggs"] = initial_eggs[:delta_chicks]
        if delta_eggs < 0:
            data["added_eggs"] = 0
            data["lost_eggs"] = initial_eggs[delta_chicks : (delta_chicks - delta_eggs)]
        else:
            data["added_eggs"] = delta_eggs
            data["lost_eggs"] = []

        return data

    def change_summary(self):
        data = self.cleaned_data
        changes = []
        for _i in range(data["added_eggs"]):
            changes.append("laid an egg")
        for hatched_egg in data["hatched_eggs"]:
            changes.append(f"{hatched_egg} hatched")
        for lost_egg in data["lost_eggs"]:
            changes.append(f"{lost_egg} lost")
        if len(changes) == 0:
            return ["no changes"]
        else:
            return changes


class NestCheckUser(forms.Form):
    confirmed = forms.BooleanField()
    entered_by = forms.ModelChoiceField(queryset=User.objects.filter(is_active=True))
    comments = forms.CharField(widget=forms.Textarea, required=False)


class NewBandForm(forms.Form):
    """Form to assign a band to an existing bird, optionally updating sex and plumage"""

    banding_date = forms.DateField()
    band_color = forms.ModelChoiceField(queryset=Color.objects.all(), required=False)
    band_number = forms.IntegerField(min_value=1)
    sex = forms.ChoiceField(choices=Animal.Sex.choices, required=True)
    plumage = forms.ModelChoiceField(queryset=Plumage.objects.all(), required=False)
    location = forms.ModelChoiceField(
        queryset=Location.objects.filter(active=True), required=False
    )
    user = forms.ModelChoiceField(queryset=User.objects.filter(is_active=True))

    def clean(self):
        data = super().clean()
        data["band_status"] = get_status_or_error(models.BANDED_EVENT_NAME)
        if Animal.objects.filter(
            band_color=data.get("band_color"), band_number=data["band_number"]
        ).exists():
            raise forms.ValidationError(
                _(
                    "A bird already exists with band color %(band_color)s and number %(band_number)d."
                ),
                code="invalid",
                params=data,
            )
        return data


class TagChangeForm(forms.Form):
    """Form to update tags on an animal.

    Adding and removing tags happens through an HTMX view, so this form just
    handles the date and user comments used to generate an event logging the
    changes.

    """

    date = forms.DateField(
        initial=timezone.now().date,
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
        help_text="Date of tag changes (defaults to today)",
        required=True,
    )
    description = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "rows": 4,
                "placeholder": "Optional comment about these tag changes...",
            }
        ),
        help_text="Optional comment to log with these changes",
    )
    entered_by = forms.ModelChoiceField(
        queryset=User.objects.filter(is_active=True),
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    def clean(self):
        data = super().clean()
        data["status"] = get_status_or_error(models.RESERVATION_EVENT_NAME)
        return data


class TagCreateForm(forms.ModelForm):
    description = forms.CharField(

birds/templates/birds/breeding_report.html
{% extends "base_view.html" %}
{% load bird_tags %}

{% block title %} meliza-lab : breeding report {% endblock %}

{% block content %}
<h2>Breeding Report</h2>
<hr/>

<table class="table table-striped">
  <thead>
    <th>current location</th>
    <th></th>
    <th>pair</th>
    <th>active</th>
    {% for date in dates %}
    <th>{{ date|date:"D m/d/Y" }}</th>
    {% endfor %}
  </thead>
  <tbody>
    {% for pairing in pairs %}
    <tr>
      <td>{{ pairing.location.room|default_if_none:"" }}</td>
      <td>{{ pairing.location.name }}</td>
      <td>
	<a href="{% url 'birds:pairing' pairing.pair.id %}">{{ pairing.pair.short_name }}</a>
      </td>
      <td>{{ pairing.pair.began_on|date:"m/d/Y" }}{% if pairing.pair.ended_on %}-<br/>{{ pairing.pair.ended_on|date:"m/d/Y" }}{% endif %}</td>
      {% for day in pairing.counts %}
      <td>
        {{ day|count_summary:"<br/>" }}
      </td>
      {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>

<h4>Nest checks</h4>

<table class="table table-striped">
  <thead>
    <th>Date</th>
    <th>User</th>
    <th>Comments</th>
  </thead>
  <tbody>
    {% for check in checks %}
    <tr>
      <td>{{ check.datetime|date:"D m/d/Y" }}</td>
      <td>{{ check.entered_by }}</td>
      <td>{{ check.comments }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<p><a href="{% url 'birds:breeding-check' %}">enter nest check for today</a></p>

{% endblock %}

birds/templates/birds/pairing_entry.html
{% extends "base_view.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %} meliza-lab : bird colony : add a pairing {% endblock title%}

{% block css %}
    <link href="{% static 'local/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
{% endblock %}

{% block scripts %}
<script src="{% static 'local/js/moment.min.js' %}"></script>
<script src="{% static 'local/js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript">
  $(function () {
  $('#datetimepicker1').datetimepicker({ pickTime: false});
  });
</script>
{% endblock %}

{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New pairing:</h3>
  </div>
  <div class="panel-body">
    <form action="" class="form-horizontal" method="post" role="form">
      {% csrf_token %}
      <p><strong>Instructions</strong>: This form is for setting up a pair for
        breeding. Fill it out when you place a male and female together in a
        cage. If you set the New Location field, the form will automatically create
        events associated with moving the sire and dam to the specified
        location.</p>

      <p>Use the <a href="{% url 'admin:birds_pairing_add' %}">admin
      interface</a> to do backentry of historical pairings.</p>

      {% if form.non_field_errors %}
      <div class="alert alert-danger">{{ form.non_field_errors }}</div>
      {% endif %}

      <div class="form-group {% if form.sire.errors %}has-error{% endif %}">
        <label for="id_sire" class="col-sm-2 control-label">Sire * </label>
        <div class="col-sm-5">
          {% render_field form.sire class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.dam.errors %}has-error{% endif %}">
        <label for="id_dam" class="col-sm-2 control-label">Dam * </label>
        <div class="col-sm-5">
          {% render_field form.dam class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.purpose.errors %}has-error{% endif %}">
        <label for="id_purpose" class="col-sm-2 control-label">Purpose</label>
        <div class="col-sm-5">
          {% render_field form.purpose class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.began_on.errors %}has-error{% endif %}">
        <label for="id_began_on" class="col-sm-2 control-label">Pairing date * </label>
        <div class="col-sm-3">
          <div class="input-group date" id="datetimepicker1">
            {% render_field form.began_on class+="form-control" data-format="MM/dd/YYYY" %}
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>

      <div class="form-group {% if form.entered_by.errors %}has-error{% endif %}">
        <label for="id_entered_by" class="col-sm-2 control-label">Entered by * </label>
        <div class="col-sm-3">
          {% render_field form.entered_by class+="form-control" %}
        </div>
      </div>


      <div class="form-group {% if form.location.errors %}has-error{% endif %}">
        <label for="id_location" class="col-sm-2 control-label">New location </label>
        <div class="col-sm-5">
          {% render_field form.location class+="form-control" %}
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Create pairing</button>
        </div>
      </div>

    </form>
  </div>
</div>

{% endblock %}

birds/templates/birds/pairing_event_entry.html
{% extends "base_view.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %} meliza-lab : bird colony : add event for pairing {% endblock title%}

{% block css %}
    <link href="{% static 'local/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
{% endblock %}

{% block scripts %}
<script src="{% static 'local/js/moment.min.js' %}"></script>
<script src="{% static 'local/js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript">
  $(function () {
  $('#datetimepicker1').datetimepicker({ pickTime: false});
  });
</script>
{% endblock %}


{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Add event for {{ pairing }}</h3>
  </div>
  <div class="panel-body">
    <form action="{% url 'birds:new_pairing_event' pairing.id %}" class="form-horizontal" method="post" role="form">
      {% csrf_token %}
      <p><strong>Instructions</strong>: This form adds an event to all the
	animals in <a href="{{ pairing.get_absolute_url }}">{{ pairing }}</a>:
	the sire, the dam, and all the progeny that were alive as of the
	selected date. Useful if you move all the birds to a new loction. Only
	dates between the start and end of the pairing are allowed. Use this
	form with some caution, as it can take some work to clean up if you make
	a mistake.</p>

      {% if form.non_field_errors %}
      <div class="alert alert-danger">{{ form.non_field_errors }}</div>
      {% endif %}

      <div class="form-group {% if form.status.errors %}has-error{% endif %}">
        <label for="id_status" class="col-sm-2 control-label">Event type * </label>
        <div class="col-sm-5">
          {% render_field form.status class+="form-control" %}
        </div>
      </div>


      <div class="form-group {% if form.date.errors %}has-error{% endif %}">
        <label for="id_date" class="col-sm-2 control-label">Event date * </label>
        <div class="col-sm-3">
          <div class="input-group date" id="datetimepicker1">
            {% render_field form.date class+="form-control" data-format="MM/dd/YYYY" %}
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>

      <div class="form-group {% if form.location.errors %}has-error{% endif %}">
        <label for="id_location" class="col-sm-2 control-label">Location</label>
        <div class="col-sm-5">
          {% render_field form.location class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.description.errors %}has-error{% endif %}">
        <label for="id_description" class="col-sm-2 control-label">Description</label>
        <div class="col-sm-5">
          {% render_field form.description class+="form-control" rows="3"%}
        </div>
      </div>

      <div class="form-group {% if form.entered_by.errors %}has-error{% endif %}">
        <label for="id_entered_by" class="col-sm-2 control-label">Entered by * </label>
        <div class="col-sm-3">
          {% render_field form.entered_by class+="form-control" %}
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Add events</button>
        </div>
      </div>
      
    </form>
  </div>
</div>

{% endblock %}

birds/templates/birds/pairing_table.html
{% load bird_tags %}
<table class="table table-striped table-condensed">
  <thead>
    <th>Dates</th>
    <th>Sire</th>
    <th>Dam</th>
    <th>Purpose</th>
    <th>Eggs Laid</th>
    <th>Eggs Hatched</th>
    <th>Oldest Living Child</th>
    <th>Comment</th>
  </thead>
  <tbody>
    {% for pairing in pairing_list %}
    <tr>
          <td><a href="{% url 'birds:pairing' pairing.id %}">{{ pairing.began_on }} — {{ pairing.ended_on|default_if_none:"" }}</a></td>
          <td><a href="{{ pairing.sire.get_absolute_url }}">{{ pairing.sire.name }}</a></td>
          <td><a href="{{ pairing.dam.get_absolute_url }}">{{ pairing.dam.name }}</a></td>
          <td>{{ pairing.purpose|default_if_none:"" }}</td>
          <td>{{ pairing.n_eggs }}</td>
          <td>{{ pairing.n_hatched }}</td>
          <td>{{ pairing.oldest_living_progeny_age|ageorblank }}</td>
      <td>{{ pairing.comment }}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>

birds/templates/birds/sample_table.html
{% load bird_tags %}

<table class="table table-striped table-condensed">
  <thead>
    <th>UUID</th>
    <th>Animal</th>
    <th>Type</th>
    <th>Location</th>
    <th>Date</th>
    <th>Experimenter</th>
  </thead>
  <tbody>
    {% for sample in sample_list %}
        <tr>
          <td><a href="{{ sample.get_absolute_url}}">{{ sample.uuid }}</td>
          <td><a href="{{ sample.animal.get_absolute_url }}">{{ sample.animal.name }}</a></td>
          <td>{{ sample.type }}</td>
          <td>{{ sample.location }}</td>
          <td>{{ sample.date }}</td>
          <td>{{ sample.collected_by }}</td>
          <td></td>
        </tr>
    {% endfor %}
  </tbody>
</table>

birds/templates/birds/tag_edit.html
{% extends "base_view.html" %}
{% load static %}

{% block title %}meliza-lab : bird colony : edit tags{% endblock %}

{% block css %}
<style>
.tag-item {
    display: inline-block;
    margin: 3px;
    padding: 6px 12px;
    border-radius: 4px;
    border: 1px solid #ddd;
    cursor: pointer;
    transition: all 0.2s ease;
}

.tag-item.active {
    background-color: #337ab7;
    color: white;
    border-color: #2e6da4;
}

.tag-item:hover {
    background-color: #f5f5f5;
    border-color: #adadad;
}

.tag-item.active:hover {
    background-color: #286090;
    border-color: #204d74;
}

.new-tag-form {
    margin-top: 20px;
    padding: 15px;
    border: 1px solid #ddd;
    border-radius: 4px;
    background-color: #f9f9f9;
}

.current-tags {
    margin-bottom: 20px;
    padding: 10px;
    background-color: #f0f8ff;
    border-radius: 4px;
}

.loading {
    opacity: 0.5;
    pointer-events: none;
}

</style>
{% endblock %}

{% block scripts %}
<script src="{% static 'birds/js/htmx.min.js' %}"></script>
<script>
// Add loading states and smooth animations
document.addEventListener('htmx:beforeRequest', function(evt) {
    evt.target.classList.add('loading');
});

document.addEventListener('htmx:afterRequest', function(evt) {
    evt.target.classList.remove('loading');
});

// Toggle new tag form
function toggleNewTagForm() {
    const form = document.getElementById('new-tag-form');
    form.style.display = form.style.display === 'none' ? 'block' : 'none';
}
</script>
{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Edit Tags: {{ animal }}</h3>
    </div>
    <div class="panel-body">
        <p><strong>Instructions:</strong> This form is used to update the tags for an animal. After selecting zero or more tags,
        set the date and enter an optional comment to generate a corresponding event in the database.</p>
        
        <div class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-2 control-label">Tags</label>
                <div class="col-sm-10">
                    <div id="tag-list" 
                         hx-target="#tag-list"
                         hx-swap="outerHTML">
                        {% include "birds/partials/tag_list.html" %}
                    </div>
                </div>
            </div>
	</div>

        <form method="post" action="{% url 'birds:update_tags' animal.uuid %}" class="form-horizontal" role="form">
            {% csrf_token %}

            <div class="form-group {% if form.date.errors %}has-error{% endif %}">
                <label for="id_date" class="col-sm-2 control-label">{{ form.date.label }} *</label>
                <div class="col-sm-3">
                    {{ form.date }}
                </div>
            </div>
            <div class="form-group {% if form.description.errors %}has-error{% endif %}">
                <label for="id_description" class="col-sm-2 control-label">{{ form.description.label }}</label>
                <div class="col-sm-5">
                    {{ form.description }}
                </div>
            </div>
            <div class="form-group {% if form.entered_by.errors %}has-error{% endif %}">
                <label for="id_entered_by" class="col-sm-2 control-label">{{ form.entered_by.label }} * </label>
                <div class="col-sm-3">
                    {{ form.entered_by }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Update tags</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}